### PR TITLE
Created branch for PyQt5/libffi7 for Ubuntu 20.04/kubuntu 20.04 compatibility

### PR DESCRIPTION
**Pull request by rfjohnso**
This branch uses PyQt5 and libffi7 in order to get the kerberossdr software to work in Ubuntu 20.04 and kubuntu 20.04.
I also updated the directions for installing with the PyQt5/libffi7 libraries.
I have tested the changes on both OS but only on one computer.
I dont know about backward compatiblity with older linux versions with PyQt5/libffi7, so I dont know if these changes can be straight up merged or not.
This is my first pull request and I am super new to python as well. so sorry if I did this pull request thing wrong or forgot anything in my repo but it seems to work for me.

### CODE REVIEW

**Comment by darksidelemm** [comment]
I'm not sure this is actually compatible with recent PyQt5 versions... all of the Widgets used in are now under PyQt5.QWidgets, not PyQt5.QtGui.

E.g. if you use your inputs from here: https://github.com/rfjohnso/kerberossdr/blob/PyQt5/_GUI/hydra_main_window_layout.py#L27

and then try and do (as an example): `page_4 = QtGui.QWidget()`
you get the following error:
```
>>> page_4 = QtGui.QWidget()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'PyQt5.QtGui' has no attribute 'QWidget'
```

This is because the QWidget class is now under QWidgets... e.g. the line should be: `page_4 = QWidget()` (with a `from PyQt5.QtWidgets import *`) earlier.

**Comment by rfjohnso** [comment]
Someone just posted a pull request for these issues. I am reviewing and will merge after testing. Thanks for letting me know.
